name: CI-CD
on:
 push:
  branches: [ main ]
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: D:/Documentos/Study/Azure/Conteiners/kubernetes-aula2/rotten-potatoes/src
          file: D:/Documentos/Study/Azure/Conteiners/kubernetes-aula2/rotten-potatoes/src/Dockerfile
          push: true
          tags: |
           alstreim14/rotten-potatoes:latest
           alstreim14/rotten-potatoes:${{ github.run_number }}
       
           

